### PR TITLE
Make the SDK compatible with .NET Core

### PR DESCRIPTION
**Pull request by mghextreme**
I changed the projects and dependencies to support .NET Core 2.0.  

Also:

- Added support for VSCode tasks
- Removed all the scripts because they can easily be run as a `dotnet` command.
- Removed packages folder, should be able to download everything from nuget.org
- Removed nuget.exe

My biggest concern is the update of RestSharp to 106.6.9, which had me change a parameter on the IO.Directus/Client/ApiClient class.

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I'm no expert on .NET (in the slightest), so I'll happily defer to you @mghextreme. 

I'm pretty sure this SDK hasn't been updated to work with v7 too.... Is that something you'd be interested in taking on @mghextreme? Directus is a mostly community driven project, and we can absolutely use your help 😄 

Let me know if you're down for it and I'll make you admin of the repo 🙂

**Comment by mghextreme** [comment]
Hello, @rijkvanzanten . Thanks so much for the merge!
I'm very new to Directus and I'm still not familiar with everything... But if we could have a close relationship with you guiding me, sounds like a cool idea!
I'll send you an email so we can talk a little bit more.

**Comment by rijkvanzanten** [comment]
Feel free to hop onto our Slack channel too! Makes communication a little easier 🙂 

[https://directus.chat](https://directus.chat)

**Comment by benhaynes** [comment]
Hey @mghextreme — thanks for the PR, and sorry it took so long to respond (we weren't "watching" this repo and didn't get an alert).

You can join us on Slack to discuss further!

https://www.directus.chat/

Eventually we would like all SDKs to be auto-generated in one place (we'd looking into Swagger but it's missing an important filter param format). In the meantime, we'd be happy to hand-over control of this repo to you and the community (since we don't know .NET).

I'm not sure that the current SDK even works, so I'm sure this is an improvement!

**Pull request merged**
